### ISSUE TITLE
Use show "recordings/snapshots/:timestamp" snapshot endpoint instead of nearest.

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-dashboardv2#379]
![image](https://user-images.githubusercontent.com/6176136/70801000-7c5b1080-1dcf-11ea-8224-6e2b3bdd66a8.png)

**Comment by ijunaid8989** [comment]
In summary, 


Looking into multiple nearest endpoint request on recordings calendar, issue seems to be, Hours Endpoint is being used to collect meta-information about snapshots, but only being used for Recording player, when you try to navigate the calendar it uses the Calendar's changed date and uses the nearest endpoint, instead of using the same meta info for snapshots, which gives the exact snapshot required. it seems like a tricky hack but not a good approach to how we should do it, when there is already a call being made to the endpoint for all Snapshots information the same should be used to load the first image on recording Canvas. 

I just changed a few changes

https://github.com/evercam/evercam-dashboardv2/pull/390

these are not programmatical fixes those are logical ones and small ones as well.

**Comment by ijunaid8989** [comment]
its done.
